name: CI
on:
  workflow_dispatch:
  pull_request:

  # triggering CI default branch improves caching
  # see https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
  push:
    branches:
      - main

jobs:
  check:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        version: ["2.12.19","2.13.13","3.3.3"]
        java-version: [ '8', '11', '21' ]
    runs-on: ${{ matrix.os }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java-version }}
          cache: sbt
      - name: lint
        run: >
          sbt ++${{ matrix.version }}
          scalafmtCheck
          test:scalafmtCheck
          scalafmtSbtCheck
      - name: test with coverage
        if: matrix.version == '2.12.19'
        run: >
          sbt ++${{ matrix.version }}
          coverage
          startDynamodbLocal
          test
          dynamodbLocalTestCleanup
          stopDynamodbLocal
      - name: test without coverage
        if: matrix.version == '2.13.13'
        run: >
          sbt ++${{ matrix.version }}
          startDynamodbLocal
          test
          dynamodbLocalTestCleanup
          stopDynamodbLocal
      - name: test without coverage
        if: matrix.version == '3.3.3'
        run: >
          sbt ++${{ matrix.version }}
          startDynamodbLocal
          scanamo/test catsEffect/test joda/test
          dynamodbLocalTestCleanup
          stopDynamodbLocal
      - name: cleanup
        run: bash <(curl -s https://codecov.io/bash)
  test_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: test docs
        run: sbt +doc
  gen_microsite:
    needs: [check,test_docs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.0'
          bundler-cache: true
      - name: setup jekyll
        run: gem install jekyll -v 4.0.0
      - name: gen microsite
        run: sbt startDynamodbLocal makeMicrosite stopDynamodbLocal
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [check,test_docs,gen_microsite]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
      - name: release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
